version: "3"
services: 
    frontend: 
        image: node:12
        volumes: 
            - ./:/var/www/html
        ports: 
            - "1234:1234"
        working_dir: /var/www/html
        command: bash -c "npm install && npm run dev"
